### ISSUE TITLE
Group settings doesn't work as expected

### ISSUE THREAD

**Issue by kdhkr** [Minecraft-Zocker-Pro/MZP-PlayerHologram#1]
Group settings doesn't work as expected. It just gives everyone the first group written in the configuration file.

**Tested environment**
Version: Paper 1.16.4 Build 331
Java: OpenJDK 11

**Comment by ludgart** [comment]
Hello,

thanks for reporting this issue. I fixed the bug in the newest version. 

Regards
ludgart
